#!/bin/sh
(set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix

basedir=`dirname "$dir"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

"../../tools/node/node" "$basedir/node_modules/bb-cli/bin/bb" "$@"
